name: near_me
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^14.3.0
  equatable: ^2.0.5
  flutter_svg: ^2.0.9
  internet_connection_checker: ^1.0.0+1
  dartz: ^0.10.1
  shared_preferences: ^2.2.2
  flutter_bloc: ^8.1.4
  http: ^1.2.0
  get_it: ^8.0.1
  geolocator: ^13.0.1
  intl: any
  google_fonts: ^6.2.1
  dart_jsonwebtoken: ^2.14.0
  permission_handler: ^11.3.1
  location: ^6.0.2
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.1
  image_picker: ^1.1.2
  flutter_secure_storage: ^9.2.4
  latlong2: ^0.9.1
  flutter_dotenv: ^5.2.1
  lib: ^0.0.3
  provider: ^6.1.2
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.3
  firebase_database: ^11.3.2
  firebase_messaging: ^15.2.4
  firebase_app_check: ^0.3.2+2
  font_awesome_flutter: ^10.8.0
  flutter_map: ^8.0.0
  web_socket_channel: ^3.0.2
  emoji_picker_flutter: ^4.3.0
  flutter_map_tile_caching: ^10.1.0
  flutter_local_notifications: ^18.0.1
  shimmer: ^3.0.0
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3
flutter_icons:
  android: true
  ios: true
  image_path: assets/logo.png



flutter:
  uses-material-design: true
  assets: 
    - assets/
    - .env